create database projeto;
use projeto

create table clientes(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	ENDEREÇO VARCHAR(100),
	TELEFONE VARCHAR(30),
	CPF INT(11)
);

DESC CLIENTES;

/* FORMA 01 - OMITINDO AS COLUNAS */

INSERT INTO CLIENTES  VALUES('JOAO','M','JOAO@GMAIL.COM','MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ','22923110',988638273);


/* FORMA 02 - COLOCANDO AS COLUNAS */

INSERT INTO CLIENTES (NOME,SEXO,EMAIL,CPF,TELEFONE,ENDEREÇO) VALUES('CELIA','F','CELIA@GMAIL.COM',541521456,'25078869','RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTES (NOME,SEXO,EMAIL,CPF,TELEFONE,ENDEREÇO) VALUES('JORGE','M',NULL,885755896,'58748895','OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');

INSERT INTO CLIENTES (NOME,SEXO, ENDEREÇO, TELEFONE, CPF) VALUES('LILIAN','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','947785696',887774856);


/* FORMA 03 - INSERT COMPACTO - SOMENTE MYSQL */

INSERT INTO CLIENTES (NOME,SEXO,EMAIL,CPF,TELEFONE,ENDEREÇO) VALUES('ANA','F','ANA@GLOBO.COM',85548962,'548556985','PRES ANTONIO CARLOS - CENTRO - SAO PAULO - SP'),
															  ('CARLA','F','CARLA@TERATI.COM.BR',7745828,'66587458','SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG');



