SEÇÃO 8 - MODELAGEM

/* PRIMEIRA FORMA NORMAL */

/*

1 - TODO CAMPO VETORIZADO SE TORNAR'A OUTRA TABELA

[AMARELO, AZUL, LARANJA, VERDE] -> CORES
[KA, FIESTA, UNO, CIVIC]-> CARROS

2 - TODO CAMPO MULTIVALORADO SE TORNAR'A OUTRA TABELA.
QUANDO O CAMPO FOR DIVIS'IVEL

3 - TODA TABELA NECESSITA DE PELO MENOS UM CAMPO QUE IDENTIFIQUE
TODO O REGISTRO COMO SENDO UNICO.
ISSO ;E O QUE CHAMAMOS DE CHAVE PRIMARIA OU PRIMARY KEY.
*/

CREATE DATABASE COMERCIO;

USE COMERCIO; 

CREATE TABLE CLIENTES (
	IDCLIENTES INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('F', 'M', 'NÃO-BINÁRIO') NOT NULL,
	EMAIL VARCHAR(30) UNIQUE,
	CPF VARCHAR(11) UNIQUE
);

CREATE TABLE ENDERECO (
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(50) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTES INT UNIQUE,						/* RELAÇÃO 1X1 = UNIQUE */
	FOREIGN KEY (ID_CLIENTES) REFERENCES CLIENTES(IDCLIENTES)
);

CREATE TABLE TELEFONE (
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	NUMERO VARCHAR (13) NOT NULL,
	TIPO ENUM ('CELULAR', 'RESIDENCIAL', 'COMERCIAL') NOT NULL,
	ID_CLIENTES INT,							/* RELAÇÃO 1Xn */
	FOREIGN KEY (ID_CLIENTES) REFERENCES CLIENTES(IDCLIENTES)
);


/* EM RELACIONAMENTO 1 X 1 A CHAVE ESTRANGEIRA FICA NA TABELA MAIS FRACA */

/* EM RELACIONAMENTO 1 X N A CHAVE ESTRANGEIRA FICARA SEMPRE NA
CARDINALIDADE N */

--INSERINDO DADOS DE CLIENTES
INSERT INTO CLIENTES VALUES(NULL,'JOAO','M','JOAOA@IG.COM','76567587887');
INSERT INTO CLIENTES VALUES(NULL,'CARLOS','M','CARLOSA@IG.COM','5464553466');
INSERT INTO CLIENTES VALUES(NULL,'ANA','F','ANA@IG.COM','456545678');
INSERT INTO CLIENTES VALUES(NULL,'CLARA','F',NULL,'5687766856');
INSERT INTO CLIENTES VALUES(NULL,'JORGE','M','JORGE@IG.COM','8756547688');
INSERT INTO CLIENTES VALUES(NULL,'CELIA','M','JCELIA@IG.COM','5767876889');

--INSERINDO DADOS DE TELEFONES
INSERT INTO TELEFONE (IDTELEFONE, TIPO, NUMERO, ID_CLIENTES) VALUES(NULL,'CELULAR','78458743',5);
INSERT INTO TELEFONE (IDTELEFONE, TIPO, NUMERO, ID_CLIENTES) VALUES(NULL,'RESIDENCIAL','56576876',5);
INSERT INTO TELEFONE (IDTELEFONE, TIPO, NUMERO, ID_CLIENTES) VALUES(NULL,'CELULAR','87866896',1);
INSERT INTO TELEFONE (IDTELEFONE, TIPO, NUMERO, ID_CLIENTES) VALUES(NULL,'COMERCIAL','54768899',2);
INSERT INTO TELEFONE (IDTELEFONE, TIPO, NUMERO, ID_CLIENTES) VALUES(NULL,'RESIDENCIAL','99667587',1);
INSERT INTO TELEFONE (IDTELEFONE, TIPO, NUMERO, ID_CLIENTES) VALUES(NULL,'CELULAR','78989765',3);
INSERT INTO TELEFONE (IDTELEFONE, TIPO, NUMERO, ID_CLIENTES) VALUES(NULL,'CELULAR','99766676',3);
INSERT INTO TELEFONE (IDTELEFONE, TIPO, NUMERO, ID_CLIENTES) VALUES(NULL,'COMERCIAL','66687899',1);
INSERT INTO TELEFONE (IDTELEFONE, TIPO, NUMERO, ID_CLIENTES) VALUES(NULL,'RESIDENCIAL','89986668',5);
INSERT INTO TELEFONE (IDTELEFONE, TIPO, NUMERO, ID_CLIENTES) VALUES(NULL,'CELULAR','88687909',2);

