SEÇÃO 18 - EXERCÍCIO OFICINA


/*  MODELO CONCEITUAL

VAMOS PRECISAR ARMAZENAR:

CLIENTE, CARRO, MARCA, COR(N), TELEFONE(0,N)
*/

CREATE DATABASE OFICINA;
USE OFICINA;


CREATE TABLE CLIENTE (
		IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
		NOME VARCHAR (30) NOT NULL,
		SEXO ENUM('F','M','NÃO-BINÁRIO'),
		ID_CARRO INT UNIQUE
);

CREATE TABLE TELEFONE (
		IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
		NUMERO VARCHAR (13) NOT NULL,
		TIPO ENUM ('RES','COM','CEL') NOT NULL,
		ID_CLIENTE INT
);

CREATE TABLE PINTURA (
		IDPINTURA INT PRIMARY KEY AUTO_INCREMENT,
		COR VARCHAR(15) NOT NULL
);

CREATE TABLE CARRO (
		IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
		MODELO VARCHAR (30) NOT NULL,
		MARCA VARCHAR (15) NOT NULL
);

CREATE TABLE CARRO_COR (
		ID_CARRO INT,
		ID_PINTURA INT,
		PRIMARY KEY (ID_CARRO, ID_COR)
);

ALTER TABLE CLIENTE 
ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY (ID_CARRO) 
REFERENCES CARRO (IDCARRO);

ALTER TABLE TELEFONE 
ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY (ID_CLIENTE) 
REFERENCES CLIENTE (IDCLIENTE);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_TA_CARROCOR_PINTURA
FOREIGN KEY (ID_PINTURA)
REFERENCES PINTURA (IDPINTURA);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_TA_CARROCOR_CARRO
FOREIGN KEY (ID_CARRO)
REFERENCES CARRO (IDCARRO);
